#spring.cloud.azure:
#  credential:
#    client-id: 50adb97
#    client-secret: ESI8Q
#  profile:
#    tenant-id: 4aed98
#  storage:
#    blob:
#      account-name: nuridevlog
#      container-name: nuri
#      endpoint: https://nuridevlog.blob.core.windows.net/
spring.cloud.azure:
  credential:
    managed-identity-enabled: true
  storage:
    blob:
      account-name: nuridevlog
      container-name: nuri
      endpoint: https://nuridevlog.blob.core.windows.net/